version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-feature:
    image: brandonwilliams2/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - FEATURE=2-search-feature.xml
      - BROWSER=chrome
    volumes:
    - "./test-output/search-feature:/usr/share/selenium-docker/test-output"
  book-flight-feature:
    image: brandonwilliams2/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - FEATURE=1-book-flight-feature.xml
      - BROWSER=firefox
    volumes:
      - "./test-output/book-flight-feature:/usr/share/selenium-docker/test-output"



