version: "3.9"
services:
  hub:
    image: selenium/hub:4.1.0
    # ports:
    # - 4444:4444
    # port mapping is optional and should only be used for testing locally to see the status of the grid

  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  search-feature:
    image: brandonwilliams2/java-selenium
    environment:
      - HUB_HOST=hub
      - FEATURE=2-search-feature.xml
      - BROWSER=chrome
    volumes:
    - "./output/search-feature-result:/usr/share/java-selenium/test-output"

  book-flight-feature:
    image: brandonwilliams2/java-selenium
    environment:
      - HUB_HOST=hub
      - FEATURE=1-book-flight-feature.xml
      - BROWSER=firefox
    volumes:
      - "./output/book-flight-feature-result:/usr/share/java-selenium/test-output"







