version: "3.9"
services:
  hub:
    image: selenium/hub:3
    networks:
      - grid

  chrome:
    image: selenium/node-chrome:3
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    networks:
      - grid

  firefox:
    image: selenium/node-firefox:3
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    networks:
      - grid

  search-feature:
    image: brandonwilliams2/selenium-docker
    environment:
      - HUB_HOST=hub
      - FEATURE=2-search-feature.xml
      - BROWSER=chrome
    volumes:
    - "./output/search-feature-result:/usr/share/selenium-docker/test-output"
    networks:
      - grid

  book-flight-feature:
    image: brandonwilliams2/selenium-docker
    environment:
      - HUB_HOST=hub
      - FEATURE=1-book-flight-feature.xml
      - BROWSER=firefox
    volumes:
      - "./output/book-flight-feature-result:/usr/share/selenium-docker/test-output"
    networks:
      - grid

networks:
  grid:






